#!/usr/bin/env bash
# changelog.sh — Generate CHANGELOG.md from git history
# Usage: bash changelog.sh [--since <tag|commit>] [--output CHANGELOG.md]

set -euo pipefail

OUTPUT="CHANGELOG.md"
SINCE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --since) SINCE="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Usage: $0 [--since <tag>] [--output <file>]"; exit 1 ;;
  esac
done

# Determine the range
if [[ -z "$SINCE" ]]; then
  # Find the latest tag, or use first commit
  SINCE=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
fi

echo "🔍 Generating changelog since: $SINCE"
echo ""

# Get commits categorized
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""

while IFS='|' read -r hash subject body; do
  # Check for conventional commit prefixes
  lower_subject=$(echo "$subject" | tr '[:upper:]' '[:lower:]')
  
  # Remove conventional commit scope if present
  clean_subject=$(echo "$subject" | sed -E 's/^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([^)]+\))?:\s*//i')
  if [[ "$clean_subject" == "$subject" ]]; then
    clean_subject="$subject"
  fi
  
  # Determine category
  case "$lower_subject" in
    feat*|add*|implem*|creat*|intro*) 
      ADDED="$ADDED\n- $clean_subject"
      ;;
    fix*|patch*|correct*|resolv*) 
      FIXED="$FIXED\n- $clean_subject"
      ;;
    remov*|delet*|deprecat*|dro*) 
      REMOVED="$REMOVED\n- $clean_subject"
      ;;
    *) 
      CHANGED="$CHANGED\n- $clean_subject"
      ;;
  esac
done < <(git log --format="%h|%s|%b" "$SINCE..HEAD" 2>/dev/null || echo "")

# Generate markdown
{
  echo "# Changelog"
  echo ""
  echo "All notable changes to this project will be documented in this file."
  echo ""
  echo "## [Unreleased]"
  echo ""
  
  if [[ -n "$ADDED" ]]; then
    echo "### Added"
    echo -e "$ADDED"
    echo ""
  fi
  
  if [[ -n "$CHANGED" ]]; then
    echo "### Changed"
    echo -e "$CHANGED"
    echo ""
  fi
  
  if [[ -n "$FIXED" ]]; then
    echo "### Fixed"
    echo -e "$FIXED"
    echo ""
  fi
  
  if [[ -n "$REMOVED" ]]; then
    echo "### Removed"
    echo -e "$REMOVED"
    echo ""
  fi
  
  echo "---"
  echo "_Generated by [changelog.sh](https://github.com/promptpolish-ai/changelog-skill)_"
} > "$OUTPUT"

echo "✅ Changelog written to: $OUTPUT"
echo ""
echo "=== Preview ==="
head -20 "$OUTPUT"
